<?xml version="1.0" encoding="utf-8"?><Database Name="BatOnBookStore" Class="NhaSachBatOnDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-R6I8CPR\SQLEXPRESS;Initial Catalog=BatOnBookStore;Integrated Security=True" SettingsObjectName="Nha_Sach_Desktop.Properties.Settings" SettingsPropertyName="BatOnBookStoreConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DANGNHAP" Member="DANGNHAPs">
    <Type Name="DANGNHAP">
      <Column Name="taikhoan" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="mahd" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="makh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tenkh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngaylap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tongtien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_PHIEUBAN" Member="PHIEUBANs" ThisKey="mahd" OtherKey="maphieuban" Type="PHIEUBAN" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="makh" OtherKey="makh" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="makh" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="makh" OtherKey="makh" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUBAN" Member="PHIEUBANs">
    <Type Name="PHIEUBAN">
      <Column Name="maphieuban" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masach" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HOADON_PHIEUBAN" Member="HOADON" ThisKey="maphieuban" OtherKey="mahd" Type="HOADON" IsForeignKey="true" />
      <Association Name="SACH_PHIEUBAN" Member="SACH" ThisKey="masach" OtherKey="masach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAP" Member="PHIEUNHAPs">
    <Type Name="PHIEUNHAP">
      <Column Name="maphieunhap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masach" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dongia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SACH_PHIEUNHAP" Member="SACH" ThisKey="masach" OtherKey="masach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SACH" Member="SACHes">
    <Type Name="SACH">
      <Column Name="masach" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="theloai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tacgia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dongia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tondau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tongnhap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tongban" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phatsinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="toncuoi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="SACH_PHIEUBAN" Member="PHIEUBANs" ThisKey="masach" OtherKey="masach" Type="PHIEUBAN" />
      <Association Name="SACH_PHIEUNHAP" Member="PHIEUNHAPs" ThisKey="masach" OtherKey="masach" Type="PHIEUNHAP" />
    </Type>
  </Table>
</Database>